language: python
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq git mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev
python: "2.7"
install:
 - pip install -r requirements.txt
 - pip install -r test-requirements.txt
# command to run tests
script:
 - cd mycroft-core
 - pep8 mycroft test
 - python test_runner.py
